# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BuscarPasajero.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from RegistrarPasajero import Ui_RegistrarPasajero


class Ui_BuscarPasajero(object):
    def setupUi(self, BuscarPasajero):
        BuscarPasajero.setObjectName("BuscarPasajero")
        BuscarPasajero.resize(524, 581)
        self.centralwidget = QtWidgets.QWidget(BuscarPasajero)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 171, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 47, 21))
        self.label_2.setObjectName("label_2")
        self.txtNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNombre.setGeometry(QtCore.QRect(100, 90, 171, 20))
        self.txtNombre.setObjectName("txtNombre")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 61, 20))
        self.label_3.setObjectName("label_3")
        self.txtCedula = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCedula.setGeometry(QtCore.QRect(100, 130, 171, 20))
        self.txtCedula.setObjectName("txtCedula")
        self.btnBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.btnBuscar.setGeometry(QtCore.QRect(290, 130, 101, 23))
        self.btnBuscar.setObjectName("btnBuscar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 170, 47, 21))
        self.label_4.setObjectName("label_4")
        self.txtEdad = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEdad.setGeometry(QtCore.QRect(100, 170, 171, 20))
        self.txtEdad.setObjectName("txtEdad")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 210, 47, 21))
        self.label_5.setObjectName("label_5")
        self.txtSexo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSexo.setGeometry(QtCore.QRect(100, 210, 171, 20))
        self.txtSexo.setObjectName("txtSexo")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 280, 91, 21))
        self.label_6.setObjectName("label_6")
        self.txtNumeroAsiento = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNumeroAsiento.setGeometry(QtCore.QRect(100, 280, 171, 20))
        self.txtNumeroAsiento.setObjectName("txtNumeroAsiento")
        self.btnCerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCerrar.setGeometry(QtCore.QRect(410, 280, 75, 23))
        self.btnCerrar.setObjectName("btnCerrar")
        self.txtMostrarPasajeros = QtWidgets.QTextEdit(self.centralwidget)
        self.txtMostrarPasajeros.setGeometry(QtCore.QRect(20, 320, 471, 161))
        self.txtMostrarPasajeros.setObjectName("txtMostrarPasajeros")
        self.btnMostrarPasajeros = QtWidgets.QPushButton(self.centralwidget)
        self.btnMostrarPasajeros.setGeometry(QtCore.QRect(170, 500, 121, 23))
        self.btnMostrarPasajeros.setObjectName("btnMostrarPasajeros")
        self.NumeroAsiento = QtWidgets.QLabel(self.centralwidget)
        self.NumeroAsiento.setGeometry(QtCore.QRect(50, 250, 81, 20))
        self.NumeroAsiento.setObjectName("NumeroAsiento")
        self.txtClase = QtWidgets.QLineEdit(self.centralwidget)
        self.txtClase.setGeometry(QtCore.QRect(100, 250, 171, 20))
        self.txtClase.setObjectName("txtClase")
        BuscarPasajero.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BuscarPasajero)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 21))
        self.menubar.setObjectName("menubar")
        BuscarPasajero.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BuscarPasajero)
        self.statusbar.setObjectName("statusbar")
        BuscarPasajero.setStatusBar(self.statusbar)
        self.retranslateUi(BuscarPasajero)
        QtCore.QMetaObject.connectSlotsByName(BuscarPasajero)
        self.btnBuscar.clicked.connect(self.LlenarCajones)
        self.btnMostrarPasajeros.clicked.connect(self.Llenar)

    def retranslateUi(self, BuscarPasajero):
        _translate = QtCore.QCoreApplication.translate
        BuscarPasajero.setWindowTitle(_translate("BuscarPasajero", "Buscar Pasajero"))
        self.label.setText(_translate("BuscarPasajero", "Datos Pasajero"))
        self.label_2.setText(_translate("BuscarPasajero", "Nombre"))
        self.label_3.setText(_translate("BuscarPasajero", "Cedula"))
        self.btnBuscar.setText(_translate("BuscarPasajero", "Buscar"))
        self.label_4.setText(_translate("BuscarPasajero", "Edad"))
        self.label_5.setText(_translate("BuscarPasajero", "Clase"))
        self.label_6.setText(_translate("BuscarPasajero", "  Ubicacion"))
        self.btnCerrar.setText(_translate("BuscarPasajero", "Cerrar"))
        self.btnMostrarPasajeros.setText(_translate("BuscarPasajero", "Mostrar Pasajeros"))
        self.NumeroAsiento.setText(_translate("BuscarPasajero", "Asiento"))

    def Llenar(self):
        for i in range(len(Ui_RegistrarPasajero.Datos1)):
            self.txtMostrarPasajeros.append(str(Ui_RegistrarPasajero.Datos1[i]))

    def LlenarCajones(self):
        self.documento = self.txtCedula.text()
        if Ui_RegistrarPasajero.Datos1.__contains__(self.documento):
            for i in range(0, len(Ui_RegistrarPasajero.Datos1), 7):
                if self.documento == Ui_RegistrarPasajero.Datos1[i]:
                    self.txtNombre.setText(Ui_RegistrarPasajero.Datos1[i + 1])
                    self.txtEdad.setText(Ui_RegistrarPasajero.Datos1[i + 2])
                    self.txtSexo.setText(Ui_RegistrarPasajero.Datos1[i + 3])
                    self.txtClase.setText(str(Ui_RegistrarPasajero.Datos1[i + 6]))
                    self.txtNumeroAsiento.setText(Ui_RegistrarPasajero.Datos1[i + 4])
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Alerta")
            msg.setText("La cédula no esta registrada")
            x = msg.exec_()
            self.txtCedula.setText("")

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    BuscarPasajero = QtWidgets.QMainWindow()
    ui = Ui_BuscarPasajero()
    ui.setupUi(BuscarPasajero)
    BuscarPasajero.show()
    sys.exit(app.exec_())
