# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DatosEstadisticos.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from RegistrarPasajero import Ui_RegistrarPasajero


class Ui_DatosEstadisticos(object):
    def setupUi(self, DatosEstadisticos):
        DatosEstadisticos.setObjectName("DatosEstadisticos")
        DatosEstadisticos.resize(443, 548)
        self.centralwidget = QtWidgets.QWidget(DatosEstadisticos)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 40, 151, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 220, 51, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 270, 51, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 320, 81, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 360, 71, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(100, 390, 47, 21))
        self.label_8.setObjectName("label_8")
        self.txtEMjoven = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEMjoven.setGeometry(QtCore.QRect(140, 390, 151, 20))
        self.txtEMjoven.setObjectName("txtEMjoven")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(100, 360, 47, 13))
        self.label_9.setObjectName("label_9")
        self.txtNMjoven = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNMjoven.setGeometry(QtCore.QRect(140, 360, 151, 20))
        self.txtNMjoven.setObjectName("txtNMjoven")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 430, 61, 21))
        self.label_10.setObjectName("label_10")
        self.txtNMviejo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNMviejo.setGeometry(QtCore.QRect(140, 430, 151, 20))
        self.txtNMviejo.setObjectName("txtNMviejo")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(90, 430, 47, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(90, 470, 47, 21))
        self.label_12.setObjectName("label_12")
        self.txtEMviejo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEMviejo.setGeometry(QtCore.QRect(140, 470, 151, 20))
        self.txtEMviejo.setObjectName("txtEMviejo")
        self.txtMasculino = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMasculino.setGeometry(QtCore.QRect(90, 120, 111, 20))
        self.txtMasculino.setObjectName("txtMasculino")
        self.txtFemenino = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFemenino.setGeometry(QtCore.QRect(90, 170, 113, 20))
        self.txtFemenino.setObjectName("txtFemenino")
        self.txtMayores = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMayores.setGeometry(QtCore.QRect(90, 220, 113, 20))
        self.txtMayores.setObjectName("txtMayores")
        self.txtMenores = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMenores.setGeometry(QtCore.QRect(90, 270, 113, 20))
        self.txtMenores.setObjectName("txtMenores")
        self.txtPromEdad = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPromEdad.setGeometry(QtCore.QRect(90, 320, 113, 20))
        self.txtPromEdad.setObjectName("txtPromEdad")
        self.btnMostrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnMostrar.setGeometry(QtCore.QRect(280, 180, 75, 23))
        self.btnMostrar.setObjectName("btnMostrar")
        DatosEstadisticos.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DatosEstadisticos)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 443, 21))
        self.menubar.setObjectName("menubar")
        DatosEstadisticos.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DatosEstadisticos)
        self.statusbar.setObjectName("statusbar")
        DatosEstadisticos.setStatusBar(self.statusbar)

        self.retranslateUi(DatosEstadisticos)
        QtCore.QMetaObject.connectSlotsByName(DatosEstadisticos)
        self.btnMostrar.clicked.connect(self.DatosEstadisticos)

    def retranslateUi(self, DatosEstadisticos):
        _translate = QtCore.QCoreApplication.translate
        DatosEstadisticos.setWindowTitle(_translate("DatosEstadisticos", "Datos Estadisticos"))
        self.label.setText(_translate("DatosEstadisticos", "Datos Estadísticos"))
        self.label_2.setText(_translate("DatosEstadisticos", "Masculino"))
        self.label_3.setText(_translate("DatosEstadisticos", "Femenino"))
        self.label_4.setText(_translate("DatosEstadisticos", "Mayores"))
        self.label_5.setText(_translate("DatosEstadisticos", "Menores"))
        self.label_6.setText(_translate("DatosEstadisticos", "Promedio edad"))
        self.label_7.setText(_translate("DatosEstadisticos", "Más joven"))
        self.label_8.setText(_translate("DatosEstadisticos", "Edad"))
        self.label_9.setText(_translate("DatosEstadisticos", "Nombre"))
        self.label_10.setText(_translate("DatosEstadisticos", "Más viejo"))
        self.label_11.setText(_translate("DatosEstadisticos", "Nombre"))
        self.label_12.setText(_translate("DatosEstadisticos", "Edad"))
        self.btnMostrar.setText(_translate("DatosEstadisticos", "Mostrar"))

    def DatosEstadisticos(self):

        masculino = int(0);

        femenino = int(0);

        for i in range(len(Ui_RegistrarPasajero.Datos1)):
            if Ui_RegistrarPasajero.Datos1[i] == "Femenino":
                femenino += 1
                self.txtFemenino.setText(str(femenino))
            elif Ui_RegistrarPasajero.Datos1[i] == "Masculino":
                masculino += 1
                self.txtMasculino.setText(str(masculino))

        self.mayores = 0

        self.menores = 0

        for i in range(2, len(Ui_RegistrarPasajero.Datos1), 7):
            if int(Ui_RegistrarPasajero.Datos1[i]) >= 18:
                self.mayores += 1
            else:
                self.menores += 1
        self.txtMenores.setText(str(self.menores))
        self.txtMayores.setText(str(self.mayores))

        self.cant = 0
        self.sum = 0

        for i in range(2, len(Ui_RegistrarPasajero.Datos1), 7):
            self.cant += 1
            self.sum += int(Ui_RegistrarPasajero.Datos1[i])
        self.promEdad = self.sum // self.cant
        self.txtPromEdad.setText(str(self.promEdad))

        self.menor = 9845678
        self.mayor = 0

        for i in range(2, len(Ui_RegistrarPasajero.Datos1), 7):
            if int(Ui_RegistrarPasajero.Datos1[i]) >= 18:
                for j in range(2, len(Ui_RegistrarPasajero.Datos1), 7):
                    if int(Ui_RegistrarPasajero.Datos1[j]) < int(Ui_RegistrarPasajero.Datos1[i]) and int(
                            Ui_RegistrarPasajero.Datos1[i]) > self.mayor:
                        self.nombreMayor = Ui_RegistrarPasajero.Datos1[i - 1]
                        self.mayor = int(Ui_RegistrarPasajero.Datos1[i])
            else:
                for j in range(2, len(Ui_RegistrarPasajero.Datos1), 7):
                    if int(Ui_RegistrarPasajero.Datos1[j]) > int(Ui_RegistrarPasajero.Datos1[i]) and int(
                            Ui_RegistrarPasajero.Datos1[i]) < self.menor:
                        self.nombreMenor = Ui_RegistrarPasajero.Datos1[i - 1]
                        self.menor = int(Ui_RegistrarPasajero.Datos1[i])
        self.txtNMviejo.setText(str(self.nombreMayor))
        self.txtEMviejo.setText(str(self.mayor))
        self.txtNMjoven.setText(str(self.nombreMenor))
        self.txtEMjoven.setText(str(self.menor))







if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    DatosEstadisticos = QtWidgets.QMainWindow()
    ui = Ui_DatosEstadisticos()
    ui.setupUi(DatosEstadisticos)
    DatosEstadisticos.show()
    sys.exit(app.exec_())
