# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EliminarPasajero.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from RegistrarPasajero import Ui_RegistrarPasajero


class Ui_EliminarPasajero(object):
    def setupUi(self, EliminarPasajero):
        EliminarPasajero.setObjectName("EliminarPasajero")
        EliminarPasajero.resize(499, 201)
        self.centralwidget = QtWidgets.QWidget(EliminarPasajero)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 151, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 131, 31))
        self.label_2.setObjectName("label_2")
        self.txtCedula = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCedula.setGeometry(QtCore.QRect(170, 80, 221, 20))
        self.txtCedula.setObjectName("txtCedula")
        self.btnAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAceptar.setGeometry(QtCore.QRect(100, 120, 91, 23))
        self.btnAceptar.setObjectName("btnAceptar")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(230, 120, 101, 23))
        self.btnCancelar.setObjectName("btnCancelar")
        EliminarPasajero.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EliminarPasajero)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 499, 21))
        self.menubar.setObjectName("menubar")
        EliminarPasajero.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EliminarPasajero)
        self.statusbar.setObjectName("statusbar")
        EliminarPasajero.setStatusBar(self.statusbar)

        self.retranslateUi(EliminarPasajero)
        QtCore.QMetaObject.connectSlotsByName(EliminarPasajero)
        self.btnAceptar.clicked.connect(self.Eliminar)

    def retranslateUi(self, EliminarPasajero):
        _translate = QtCore.QCoreApplication.translate
        EliminarPasajero.setWindowTitle(_translate("EliminarPasajero", "Eliminar Pasajero"))
        self.label.setText(_translate("EliminarPasajero", "Eliminar Pasajero"))
        self.label_2.setText(_translate("EliminarPasajero", "Ingrese número de cédula"))
        self.btnAceptar.setText(_translate("EliminarPasajero", "Aceptar"))
        self.btnCancelar.setText(_translate("EliminarPasajero", "Cancelar"))

    def Eliminar(self):

        self.cedula = self.txtCedula.text()
        if Ui_RegistrarPasajero.Datos1.__contains__(self.cedula):
            for i in range(0, len(Ui_RegistrarPasajero.Datos1), 7):
                if self.cedula == Ui_RegistrarPasajero.Datos1[i]:
                    self.asiento = int(Ui_RegistrarPasajero.Datos1[i + 6])
                    if Ui_RegistrarPasajero.Datos1[i + 4] == "Ejecutiva":
                        if Ui_RegistrarPasajero.Datos1[i + 5] == "Ventana":
                            Ui_RegistrarPasajero.ejecutivaVentana.append(self.asiento)
                            for j in range(len(Ui_RegistrarPasajero.asientoReservado)):
                                if self.asiento == Ui_RegistrarPasajero.asientoReservado[j]:
                                    Ui_RegistrarPasajero.asientoReservado.pop(j)
                        else:
                            Ui_RegistrarPasajero.ejecutivaPasillo.append(self.asiento)
                            for j in range(len(Ui_RegistrarPasajero.asientoReservado)):
                                if self.asiento == Ui_RegistrarPasajero.asientoReservado[j]:
                                    Ui_RegistrarPasajero.asientoReservado.pop(j)
                    else:
                        if Ui_RegistrarPasajero.Datos1[i + 5] == "Ventana":
                            Ui_RegistrarPasajero.economicaVentana.append(self.asiento)
                            for j in range(len(Ui_RegistrarPasajero.asientoReservado)):
                                if self.asiento == Ui_RegistrarPasajero.asientoReservado[j]:
                                    Ui_RegistrarPasajero.asientoReservado.pop(j)
                        elif Ui_RegistrarPasajero.Datos1[i + 5] == "Centro":
                            Ui_RegistrarPasajero.economicaVentana.append(self.asiento)
                            for j in range(len(Ui_RegistrarPasajero.asientoReservado)):
                                if self.asiento == Ui_RegistrarPasajero.asientoReservado[j]:
                                    Ui_RegistrarPasajero.asientoReservado.pop(j)
                        else:
                            Ui_RegistrarPasajero.economicaVentana.append(self.asiento)
                            for j in range(len(Ui_RegistrarPasajero.asientoReservado)):
                                if self.asiento == Ui_RegistrarPasajero.asientoReservado[j]:
                                    Ui_RegistrarPasajero.asientoReservado.pop(j)
                    Ui_RegistrarPasajero.Datos1.pop(i)
                    Ui_RegistrarPasajero.Datos1.pop(i)
                    Ui_RegistrarPasajero.Datos1.pop(i)
                    Ui_RegistrarPasajero.Datos1.pop(i)
                    Ui_RegistrarPasajero.Datos1.pop(i)
                    Ui_RegistrarPasajero.Datos1.pop(i)
                    Ui_RegistrarPasajero.Datos1.pop(i)
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Información")
            msg.setText("No se ha eliminado. ")
            x = msg.exec_()

        print(Ui_RegistrarPasajero.Datos1)
        print(Ui_RegistrarPasajero.asientoReservado)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    EliminarPasajero = QtWidgets.QMainWindow()
    ui = Ui_EliminarPasajero()
    ui.setupUi(EliminarPasajero)
    EliminarPasajero.show()
    sys.exit(app.exec_())
