# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegistrarPasajero.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QDialog, QMessageBox


class Ui_RegistrarPasajero(object):
    Datos1 = []
    ejecutivaVentana = [1, 5, 4, 8]
    ejecutivaPasillo = [2, 6, 3, 7]
    economicaVentana = [9, 15, 21, 27, 33, 39, 45, 14, 20, 26, 32, 38, 44, 50]
    economicaCentro = [10, 16, 22, 28, 34, 40, 46, 13, 19, 25, 31, 37, 43, 49]
    economicaPasillo = [11, 17, 23, 29, 35, 41, 47, 12, 18, 24, 30, 36, 42, 48]
    asientoReservado = []

    def setupUi(self, RegistrarPasajero):
        RegistrarPasajero.setObjectName("RegistrarPasajero")
        RegistrarPasajero.resize(320, 441)
        self.centralwidget = QtWidgets.QWidget(RegistrarPasajero)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 47, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 47, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 51, 31))
        self.label_4.setObjectName("label_4")
        self.radioMasculino = QtWidgets.QRadioButton(self.centralwidget)
        self.radioMasculino.setGeometry(QtCore.QRect(90, 170, 82, 17))
        self.radioMasculino.setChecked(True)
        self.radioMasculino.setObjectName("radioMasculino")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(RegistrarPasajero)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioMasculino)
        self.radioFemenino = QtWidgets.QRadioButton(self.centralwidget)
        self.radioFemenino.setGeometry(QtCore.QRect(200, 170, 82, 17))
        self.radioFemenino.setObjectName("radioFemenino")
        self.buttonGroup_2.addButton(self.radioFemenino)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 260, 47, 21))
        self.label_5.setObjectName("label_5")
        self.cmbClase = QtWidgets.QComboBox(self.centralwidget)
        self.cmbClase.setGeometry(QtCore.QRect(90, 260, 191, 22))
        self.cmbClase.setObjectName("cmbClase")
        self.cmbClase.addItem("")
        self.cmbClase.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 310, 47, 21))
        self.label_6.setObjectName("label_6")
        self.cmbUbicacion = QtWidgets.QComboBox(self.centralwidget)
        self.cmbUbicacion.setGeometry(QtCore.QRect(90, 310, 191, 22))
        self.cmbUbicacion.setObjectName("cmbUbicacion")
        self.btnRegistrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegistrar.setGeometry(QtCore.QRect(60, 350, 75, 23))
        self.btnRegistrar.setObjectName("btnRegistrar")
        self.txtCedula = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCedula.setGeometry(QtCore.QRect(90, 90, 201, 20))
        self.txtCedula.setObjectName("txtCedula")
        self.txtNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNombre.setGeometry(QtCore.QRect(90, 130, 201, 20))
        self.txtNombre.setObjectName("txtNombre")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(170, 350, 91, 23))
        self.btnCancelar.setObjectName("btnCancelar")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 220, 47, 21))
        self.label_7.setObjectName("label_7")
        self.txtEdad = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEdad.setGeometry(QtCore.QRect(90, 220, 191, 20))
        self.txtEdad.setObjectName("txtEdad")
        RegistrarPasajero.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RegistrarPasajero)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        RegistrarPasajero.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RegistrarPasajero)
        self.statusbar.setObjectName("statusbar")
        RegistrarPasajero.setStatusBar(self.statusbar)
        self.retranslateUi(RegistrarPasajero)
        QtCore.QMetaObject.connectSlotsByName(RegistrarPasajero)
        self.cmbClase.currentIndexChanged[int].connect(self.llenarUbicacion)
        self.btnRegistrar.clicked.connect(self.Variables)

    def retranslateUi(self, RegistrarPasajero):
        _translate = QtCore.QCoreApplication.translate
        RegistrarPasajero.setWindowTitle(_translate("RegistrarPasajero", "Registrar Pasajero"))
        self.label.setText(_translate("RegistrarPasajero", "Datos Pasajero"))
        self.label_2.setText(_translate("RegistrarPasajero", "Cedula"))
        self.label_3.setText(_translate("RegistrarPasajero", "Nombre"))
        self.label_4.setText(_translate("RegistrarPasajero", "Sexo"))
        self.radioMasculino.setText(_translate("RegistrarPasajero", "Masculino"))
        self.radioFemenino.setText(_translate("RegistrarPasajero", "Femenino"))
        self.label_5.setText(_translate("RegistrarPasajero", "Clase"))
        self.cmbClase.setCurrentText(_translate("RegistrarPasajero", "Clase Ejecutiva"))
        self.cmbClase.setItemText(0, _translate("RegistrarPasajero", "Clase Ejecutiva"))
        self.cmbClase.setItemText(1, _translate("RegistrarPasajero", "Clase Economica"))
        self.label_6.setText(_translate("RegistrarPasajero", "Ubicacion"))
        self.btnRegistrar.setText(_translate("RegistrarPasajero", "Registrar"))
        self.btnCancelar.setText(_translate("RegistrarPasajero", "Cancelar"))
        self.label_7.setText(_translate("RegistrarPasajero", "Edad"))

    def llenarUbicacion(self):
        self.cmbUbicacion.clear()
        self.clase = self.cmbClase.currentText()
        if self.clase == "Clase Ejecutiva":
            self.cmbUbicacion.addItem("Ventana")
            self.cmbUbicacion.addItem("Pasillo")
        elif self.clase == "Clase Economica":
            self.cmbUbicacion.addItem("Ventana")
            self.cmbUbicacion.addItem("Centro")
            self.cmbUbicacion.addItem("Pasillo")

    def Variables(self):

        self.cedula = self.txtCedula.text()
        self.nombre = self.txtNombre.text()
        self.edad = self.txtEdad.text()
        self.clase = self.cmbClase.currentText()
        self.ubicacion = self.cmbUbicacion.currentText()

        if self.radioMasculino.isChecked():
            self.sexo = "Masculino"
        else:
            self.sexo = "Femenino"

        Ui_RegistrarPasajero.Datos1.append(self.cedula)
        if (len(self.Datos1) > 1):
            for i in range(0, len(self.Datos1), 8):
                if self.Datos1[i] == self.cedula:
                    msg = QMessageBox()
                    msg.setWindowTitle("Alerta")
                    msg.setText("Ya la cédula esta asignada.")
                    x = msg.exec_()
                    self.Datos1.pop(len(self.Datos1) - 1)
                    self.txtNombre.setText("")
                    self.txtEdad.setText("")
                    self.txtCedula.setText("")
                    return

        Ui_RegistrarPasajero.Datos1.append(self.nombre)
        Ui_RegistrarPasajero.Datos1.append(self.edad)
        Ui_RegistrarPasajero.Datos1.append(self.sexo)
        Ui_RegistrarPasajero.Datos1.append(self.clase)
        Ui_RegistrarPasajero.Datos1.append(self.ubicacion)

        if self.clase == "Clase Ejecutiva":
            if "Ventana" == self.ubicacion and len(self.ejecutivaVentana) == 0 or "Pasillo" == self.ubicacion and len(
                    self.ejecutivaPasillo) == 0:
                msg = QMessageBox()
                msg.setWindowTitle("Alerta")
                msg.setText("No hay asientos disponibles en esta ubicación")
                x = msg.exec_()
                self.txtNombre.setText("")
                self.txtEdad.setText("")
                self.txtCedula.setText("")
                return
        else:
            if "Ventana" == self.ubicacion and len(self.economicaVentana) == 0 or "Centro" == self.ubicacion and len(
                    self.economicaCentro) == 0 or "Pasillo" == self.ubicacion and len(self.economicaPasillo) == 0:
                msg = QMessageBox()
                msg.setWindowTitle("Alerta")
                msg.setText("No hay asientos disponibles en esta ubicación")
                x = msg.exec_()
                self.txtNombre.setText("")
                self.txtEdad.setText("")
                self.txtCedula.setText("")
                return

        if len(self.txtCedula.text().strip()) == 0 or len(self.txtNombre.text().strip()) == 0 or len(
                self.txtEdad.text().strip()) == 0:
            msg = QMessageBox()
            msg.setWindowTitle("Alerta")
            msg.setText("Uno de los campos esta vacio.")
            x = msg.exec_()
            return

        if self.clase == "Clase Ejecutiva":
            if self.ubicacion == "Ventana":
                self.Datos1.append(self.ejecutivaVentana[0])
                self.asientoReservado.append(self.ejecutivaVentana[0])
                self.ejecutivaVentana.pop(0)
            elif self.ubicacion == "Pasillo":
                self.Datos1.append(self.ejecutivaPasillo[0])
                self.asientoReservado.append((self.ejecutivaPasillo[0]))
                self.ejecutivaPasillo.pop(0)
        elif self.clase == "Clase Economica":
            if self.ubicacion == "Ventana":
                self.Datos1.append(self.economicaVentana[0])
                self.asientoReservado.append(self.economicaVentana[0])
                self.economicaVentana.pop(0)
            elif self.clase == "Pasillo":
                self.Datos1.append(self.economicaPasillo[0])
                self.asientoReservado.append(self.economicaPasillo[0])
                self.economicaPasillo.pop(0)
            else:
                self.Datos1.append(self.economicaCentro[0])
                self.asientoReservado.append(self.economicaCentro[0])
                self.economicaCentro.pop(0)

        print(Ui_RegistrarPasajero.Datos1)
        print(self.asientoReservado)

        msg = QMessageBox()
        msg.setWindowTitle("Información")
        msg.setText("Se ha registrado")
        x = msg.exec_()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    RegistrarPasajero = QtWidgets.QMainWindow()
    ui = Ui_RegistrarPasajero()
    ui.setupUi(RegistrarPasajero)
    RegistrarPasajero.show()
    sys.exit(app.exec_())
